use std::fmt::Write;

/// Editor/tool-only modules a runtime consumer never needs. Their schemas
/// pull in large editor-only type graphs (and Windows-macro enum name
/// collisions like RELATIVE/ABSOLUTE) that don't belong in the runtime
/// amalgamation. Per-module headers are still written to `schemas/`.
const WINDOWS_SCHEMA_MACROS: &[&str] = &[
    "RELATIVE",
    "ABSOLUTE",
    "DIFFERENCE",
    "OPTIONAL",
    "IN",
    "OUT",
    "ERROR",
    "IGNORE",
    "TRANSPARENT",
    "OPAQUE",
    "PASSTHROUGH",
];

pub const EDITOR_MODULES: &[&str] = &[
    "assetbrowser_dll",
    "assetpreview_dll",
    "assetrename_dll",
    "met_dll",
    "modtools_dll",
    "resourcecompiler_dll",
];

/// Render a single include that references the files emitted by this run.
/// Optional reports are guarded with `__has_include` so `--skip-patterns`
/// remains compatible with the same header.
pub fn render_hpp(sdk_modules: &[&str], build_number: Option<u32>) -> String {
    let mut s = String::new();
    writeln!(
        s,
        "// Generated by cs2-dumper — single-include amalgamation"
    )
    .ok();
    writeln!(s, "//").ok();
    writeln!(s, "// Add the dump directory to your include path and:").ok();
    writeln!(s, "//     #include <cs2.hpp>").ok();
    writeln!(s, "//").ok();
    writeln!(
        s,
        "// The flat multi-language outputs (offsets.hpp, client_dll.hpp, sdk/sdk.hpp)"
    )
    .ok();
    writeln!(
        s,
        "// remain available for existing consumers. This header prefers the"
    )
    .ok();
    writeln!(
        s,
        "// namespaced include-tree (macros.hpp + schemas/) when present."
    )
    .ok();
    writeln!(s, "#pragma once").ok();
    if let Some(build) = build_number {
        writeln!(s, "inline constexpr unsigned int CS2_BUILD = {build};").ok();
    }
    writeln!(s).ok();

    writeln!(s, "#if __has_include(\"macros.hpp\")").ok();
    writeln!(s, "#include \"macros.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s).ok();

    let mut ordered_modules: Vec<&str> = sdk_modules
        .iter()
        .copied()
        .filter(|m| !EDITOR_MODULES.contains(m))
        .collect();
    if ordered_modules.contains(&"server_dll") && ordered_modules.contains(&"client_dll") {
        ordered_modules.retain(|m| *m != "client_dll");
        if let Some(pos) = ordered_modules.iter().position(|m| *m == "server_dll") {
            ordered_modules.insert(pos, "client_dll");
        } else {
            ordered_modules.insert(0, "client_dll");
        }
    }

    if !ordered_modules.is_empty() {
        writeln!(s, "// Per-module schema classes (editor modules omitted)").ok();
        writeln!(
            s,
            "// Neutralize Windows.h macros that collide with schema enums."
        )
        .ok();
        for mac in WINDOWS_SCHEMA_MACROS {
            writeln!(s, "#pragma push_macro(\"{mac}\")").ok();
            writeln!(s, "#undef {mac}").ok();
        }
        for m in &ordered_modules {
            writeln!(s, "#if __has_include(\"schemas/{m}.hpp\")").ok();
            writeln!(s, "#include \"schemas/{m}.hpp\"").ok();
            writeln!(s, "#endif").ok();
        }
        for mac in WINDOWS_SCHEMA_MACROS.iter().rev() {
            writeln!(s, "#pragma pop_macro(\"{mac}\")").ok();
        }
        writeln!(s).ok();
    } else {
        writeln!(s, "#if __has_include(\"sdk/sdk.hpp\")").ok();
        writeln!(s, "#include \"sdk/sdk.hpp\"").ok();
        writeln!(s, "#endif").ok();
        writeln!(s, "#if __has_include(\"sdk/modules.hpp\")").ok();
        writeln!(s, "#include \"sdk/modules.hpp\"").ok();
        writeln!(s, "#endif").ok();
        writeln!(s).ok();
    }

    writeln!(s, "#if __has_include(\"offsets/offsets.hpp\")").ok();
    writeln!(s, "#include \"offsets/offsets.hpp\"").ok();
    writeln!(s, "#elif __has_include(\"offsets_merged.hpp\")").ok();
    writeln!(s, "#include \"offsets_merged.hpp\"").ok();
    writeln!(s, "#elif __has_include(\"offsets.hpp\")").ok();
    writeln!(s, "#include \"offsets.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"interfaces/interfaces.hpp\")").ok();
    writeln!(s, "#include \"interfaces/interfaces.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"buttons.hpp\")").ok();
    writeln!(s, "#include \"buttons.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"netvars/netvars.hpp\")").ok();
    writeln!(s, "#include \"netvars/netvars.hpp\"").ok();
    writeln!(s, "#elif __has_include(\"netvars.hpp\")").ok();
    writeln!(s, "#include \"netvars.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"protobufs/protobufs.hpp\")").ok();
    writeln!(s, "#include \"protobufs/protobufs.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"impl/entity_system.hpp\")").ok();
    writeln!(s, "#include \"impl/entity_system.hpp\"").ok();
    writeln!(s, "#elif __has_include(\"entity_system.hpp\")").ok();
    writeln!(s, "#include \"entity_system.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"patterns/patterns.hpp\")").ok();
    writeln!(s, "#include \"patterns/patterns.hpp\"").ok();
    writeln!(s, "#elif __has_include(\"patterns.hpp\")").ok();
    writeln!(s, "#include \"patterns.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"vtables.hpp\")").ok();
    writeln!(s, "#include \"vtables.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"engine/ccsgoinput.h\")").ok();
    writeln!(s, "#include \"engine/ccsgoinput.h\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"engine/cusercmd.h\")").ok();
    writeln!(s, "#include \"engine/cusercmd.h\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"engine/cviewsetup.h\")").ok();
    writeln!(s, "#include \"engine/cviewsetup.h\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"structs.hpp\")").ok();
    writeln!(s, "#include \"structs.hpp\"").ok();
    writeln!(s, "#endif").ok();
    s
}

#[cfg(test)]
mod tests {
    use super::render_hpp;

    #[test]
    fn omits_editor_modules_and_orders_client_before_server() {
        let header = render_hpp(
            &["server_dll", "assetbrowser_dll", "client_dll"],
            Some(14152),
        );
        assert!(header.contains("CS2_BUILD = 14152"));
        assert!(header.contains("schemas/client_dll.hpp"));
        assert!(header.contains("schemas/server_dll.hpp"));
        assert!(!header.contains("assetbrowser_dll"));
        let client = header.find("schemas/client_dll.hpp").unwrap();
        let server = header.find("schemas/server_dll.hpp").unwrap();
        assert!(client < server);
        assert!(header.contains("#pragma push_macro(\"RELATIVE\")"));
        assert!(header.contains("#undef RELATIVE"));
        let push = header.find("#pragma push_macro(\"RELATIVE\")").unwrap();
        let pop = header.rfind("#pragma pop_macro(\"RELATIVE\")").unwrap();
        assert!(push < client && client < pop);
    }

    #[test]
    fn falls_back_to_flat_sdk_when_no_schema_modules() {
        let header = render_hpp(&[], None);
        assert!(header.contains("sdk/sdk.hpp"));
        assert!(header.contains("__has_include"));
    }
}
