use std::fmt::Write;

use crate::analysis::OffsetMap;

/// Standalone helper emitted at the dump root. It consumes
/// `offsets_merged.hpp` (pattern + canonical + interface RVAs).
pub fn render_hpp(build_number: Option<u32>) -> String {
    let mut s = String::new();
    writeln!(s, "// Generated by cs2-dumper - entity system helper").ok();
    writeln!(s, "#pragma once").ok();
    writeln!(s, "#include <cstdint>").ok();
    writeln!(s, "#include <cstddef>").ok();
    writeln!(s, "#include <Windows.h>").ok();
    writeln!(s, "#include \"offsets_merged.hpp\"\n").ok();
    if let Some(build) = build_number {
        writeln!(
            s,
            "namespace cs2_entity {{ inline constexpr std::uint32_t CS2_BUILD = {build}; }}\n"
        )
        .ok();
    }
    writeln!(s, "namespace cs2_entity {{").ok();
    writeln!(s, "inline constexpr std::size_t kChunkArrayOffset = 0x10;").ok();
    writeln!(s, "inline constexpr std::size_t kChunkPointerStride = 0x8;").ok();
    writeln!(s, "inline constexpr std::size_t kIdentityStride = 0x70;").ok();
    writeln!(
        s,
        "inline constexpr std::size_t kDesignerNameOffset = 0x20;"
    )
    .ok();
    writeln!(s, "inline constexpr std::size_t kMaxEntities = 32768;").ok();
    writeln!(s).ok();
    writeln!(s, "inline std::uintptr_t client_base() noexcept {{").ok();
    writeln!(
        s,
        "    return reinterpret_cast<std::uintptr_t>(::GetModuleHandleA(\"client.dll\"));"
    )
    .ok();
    writeln!(s, "}}").ok();
    writeln!(s).ok();
    writeln!(s, "inline std::uintptr_t entity_system() noexcept {{").ok();
    writeln!(s, "    const auto base = client_base();").ok();
    writeln!(s, "    if (!base) return 0;").ok();
    writeln!(
        s,
        "    return *reinterpret_cast<std::uintptr_t*>(base + offsets::client::GameEntitySystem);"
    )
    .ok();
    writeln!(s, "}}").ok();
    writeln!(s).ok();
    writeln!(
        s,
        "inline void* entity_by_index(std::size_t index) noexcept {{"
    )
    .ok();
    writeln!(s, "    if (index >= kMaxEntities) return nullptr;").ok();
    writeln!(s, "    const auto system = entity_system();").ok();
    writeln!(s, "    if (!system) return nullptr;").ok();
    writeln!(s, "    const auto chunk = *reinterpret_cast<std::uintptr_t*>(system + kChunkArrayOffset + (index / 512) * kChunkPointerStride);").ok();
    writeln!(s, "    if (!chunk) return nullptr;").ok();
    writeln!(
        s,
        "    const auto identity = chunk + (index % 512) * kIdentityStride;"
    )
    .ok();
    writeln!(s, "    return *reinterpret_cast<void**>(identity);").ok();
    writeln!(s, "}}").ok();
    writeln!(s).ok();
    writeln!(
        s,
        "inline const char* designer_name(std::size_t index) noexcept {{"
    )
    .ok();
    writeln!(s, "    if (index >= kMaxEntities) return nullptr;").ok();
    writeln!(s, "    const auto system = entity_system();").ok();
    writeln!(s, "    if (!system) return nullptr;").ok();
    writeln!(s, "    const auto chunk = *reinterpret_cast<std::uintptr_t*>(system + kChunkArrayOffset + (index / 512) * kChunkPointerStride);").ok();
    writeln!(s, "    if (!chunk) return nullptr;").ok();
    writeln!(
        s,
        "    const auto identity = chunk + (index % 512) * kIdentityStride;"
    )
    .ok();
    writeln!(
        s,
        "    return *reinterpret_cast<const char**>(identity + kDesignerNameOffset);"
    )
    .ok();
    writeln!(s, "}}").ok();
    writeln!(s).ok();
    writeln!(s, "inline void* local_player_controller() noexcept {{").ok();
    writeln!(s, "    const auto base = client_base();").ok();
    writeln!(s, "    if (!base) return nullptr;").ok();
    writeln!(
        s,
        "    return *reinterpret_cast<void**>(base + offsets::client::LocalPlayerController);"
    )
    .ok();
    writeln!(s, "}}").ok();
    writeln!(s, "}} // namespace cs2_entity").ok();
    s
}

/// Typed include-tree helper under `impl/`. Uses `offsets::` constants plus
/// schema classes when `schemas/client_dll.hpp` is available.
pub fn render_impl_hpp(_offsets: &OffsetMap, build_number: Option<u32>) -> String {
    let mut s = String::new();

    writeln!(s, "// Generated by cs2-dumper — entity system helpers").ok();
    writeln!(s, "#pragma once").ok();
    writeln!(s).ok();
    writeln!(s, "#include <cstdint>").ok();
    writeln!(s, "#include <windows.h>").ok();
    writeln!(s, "#if __has_include(\"../offsets/offsets.hpp\")").ok();
    writeln!(s, "#include \"../offsets/offsets.hpp\"").ok();
    writeln!(s, "#elif __has_include(\"../offsets_merged.hpp\")").ok();
    writeln!(s, "#include \"../offsets_merged.hpp\"").ok();
    writeln!(s, "#else").ok();
    writeln!(s, "#include \"../offsets.hpp\"").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "#if __has_include(\"../schemas/client_dll.hpp\")").ok();
    writeln!(s, "#include \"../schemas/client_dll.hpp\"").ok();
    writeln!(s, "#define CS2_DUMPER_HAS_CLIENT_SCHEMA 1").ok();
    writeln!(s, "#endif").ok();
    writeln!(s).ok();

    if let Some(bn) = build_number {
        writeln!(
            s,
            "namespace entity {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n"
        )
        .ok();
    }

    writeln!(s, "struct CGameEntitySystem {{").ok();
    writeln!(s, "    // Offset of the entity-list chunk-pointer array within CGameEntitySystem.").ok();
    writeln!(s, "    static constexpr std::size_t kEntityListOffset = 0x10;").ok();
    writeln!(s, "    static constexpr std::size_t kIdentityStride    = 0x70;").ok();
    writeln!(s, "    static constexpr int          kChunkSize         = 512;").ok();
    writeln!(s, "    static constexpr int          kMaxEntities       = 32768;").ok();
    writeln!(s).ok();

    writeln!(s, "    static int GetHighestEntityIndex() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return 0;").ok();
    writeln!(s, "        auto es = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!es) return 0;").ok();
    writeln!(s, "        return *reinterpret_cast<int*>(es + offsets::client::GameEntitySystem_highestEntityIndex);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "#if CS2_DUMPER_HAS_CLIENT_SCHEMA").ok();
    writeln!(s, "    static client::CCSPlayerController* GetLocalPlayer() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<client::CCSPlayerController**>(client + offsets::client::LocalPlayerController);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();
    writeln!(s, "    static client::CEntityIdentity* GetIdentityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0) return nullptr;").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!entity_system) return nullptr;").ok();
    writeln!(s, "        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + kEntityListOffset + static_cast<std::size_t>(index / kChunkSize) * 8);").ok();
    writeln!(s, "        if (!chunk) return nullptr;").ok();
    writeln!(s, "        return reinterpret_cast<client::CEntityIdentity*>(chunk + static_cast<std::size_t>(index % kChunkSize) * kIdentityStride);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s, "#else").ok();
    writeln!(s, "    static void* GetLocalPlayer() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<void**>(client + offsets::client::LocalPlayerController);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s, "#endif").ok();
    writeln!(s).ok();

    writeln!(s, "    static void* GetEntityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0 || index >= kMaxEntities) return nullptr;").ok();
    writeln!(s, "#if CS2_DUMPER_HAS_CLIENT_SCHEMA").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<void**>(identity);").ok();
    writeln!(s, "#else").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!entity_system) return nullptr;").ok();
    writeln!(s, "        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + kEntityListOffset + static_cast<std::size_t>(index / kChunkSize) * 8);").ok();
    writeln!(s, "        if (!chunk) return nullptr;").ok();
    writeln!(s, "        auto identity = chunk + static_cast<std::size_t>(index % kChunkSize) * kIdentityStride;").ok();
    writeln!(s, "        return *reinterpret_cast<void**>(identity);").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    static const char* GetDesignerName(int index) noexcept {{").ok();
    writeln!(s, "#if CS2_DUMPER_HAS_CLIENT_SCHEMA").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity || !GetEntityByIndex(index)) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<const char**>(&identity->m_designerName());").ok();
    writeln!(s, "#else").ok();
    writeln!(s, "        auto* entity = GetEntityByIndex(index);").ok();
    writeln!(s, "        if (!entity) return nullptr;").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!entity_system) return nullptr;").ok();
    writeln!(s, "        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + kEntityListOffset + static_cast<std::size_t>(index / kChunkSize) * 8);").ok();
    writeln!(s, "        if (!chunk) return nullptr;").ok();
    writeln!(s, "        auto identity = chunk + static_cast<std::size_t>(index % kChunkSize) * kIdentityStride;").ok();
    writeln!(s, "        return *reinterpret_cast<const char**>(identity + 0x20);").ok();
    writeln!(s, "#endif").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "}};").ok();
    writeln!(s).ok();
    s
}
