//! Combined interfaces header.
//!
//! Emits `interfaces/interfaces.hpp` with everything under one `ifc::` namespace:
//!
//! - `ifc::<module>::<Class>` — abstract C++ structs whose pure-virtuals are
//!   declared in vtable-slot order so layout mirrors the game's.
//! - `ifc::<ShortName>()` — zero-argument top-level accessors that resolve the
//!   module via GetModuleHandleA and return a ready-to-use typed pointer.
//!
//! Usage:
//! ```cpp
//! ifc::InputSystem()->SetRelativeMouseMode(false);
//! ifc::EnginePVSManager()->SetPvsEnabled(false);
//! ifc::MaterialSystem2()->...;
//! ifc::LocalPlayerController()->m_iTeamNum();
//! ```

use std::borrow::Cow;
use std::collections::BTreeMap;
use std::fmt::Write;

use crate::analysis::InterfaceMap;

use super::ident::{cpp_identifier, sanitize_ident, type_ident, IdentifierAllocator};
use super::comment_text;

pub struct Method<'a> {
    pub index: usize,
    /// Pattern-recovered name for this slot, when known.
    pub name: Option<&'a str>,
}

pub struct IfaceClass<'a> {
    pub module: &'a str,
    pub iface_name: &'a str,
    /// RVA of the resolved singleton instance in `module`, when available.
    /// This lets the generated header provide a typed accessor without
    /// baking a process-specific absolute address.
    pub instance_rva: Option<u64>,
    /// Owned only for RTTI names recovered by the manual pattern walk;
    /// registered-interface classes borrow `VTableInfo::rtti_class`.
    pub rtti_class: Option<Cow<'a, str>>,
    pub methods: Vec<Method<'a>>,
    /// True for classes discovered via pattern + RTTI walk rather than
    /// CreateInterface registration. Affects rendering only at the struct
    /// banner — `iface:` is shown as empty.
    pub manual: bool,
}

struct Curated {
    ret: &'static str,
    name: &'static str,
    params: &'static [&'static str],
}

fn curated(module: &str, class: &str, index: usize) -> Option<Curated> {
    match (module, class, index) {
        ("inputsystem.dll", "CInputSystem", 76) => Some(Curated {
            ret: "void",
            name: "SetRelativeMouseMode",
            params: &["bool"],
        }),
        ("panorama.dll", "CPanoramaUIEngine", 13) => Some(Curated {
            ret: "void*",
            name: "GetUIEngine",
            params: &[],
        }),
        ("engine2.dll", "CEnginePVSManager", 6) => Some(Curated {
            ret: "void",
            name: "SetPvsEnabled",
            params: &["bool"],
        }),
        _ => None,
    }
}

fn module_ns(module: &str) -> Cow<'_, str> {
    sanitize_ident(module.trim_end_matches(".dll"))
}

fn class_ns(c: &IfaceClass<'_>) -> String {
    c.rtti_class
        .as_deref()
        .map(cpp_identifier)
        .unwrap_or_else(|| cpp_identifier(type_ident(c.iface_name).as_ref()))
}

pub fn render_hpp(
    _interfaces: &InterfaceMap,
    classes: &[IfaceClass<'_>],
    build_number: Option<u32>,
) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("//\n");
    s.push_str("// CS2 interfaces — typed vtable structs in `ifc::<module>::<Class>`.\n");
    s.push_str("// Resolved singleton RVAs are exposed as constants in offsets.hpp\n");
    s.push_str("// (with a `p` prefix when one runtime dereference is needed). Build\n");
    s.push_str("// the typed pointer at the call site or in a project-local wrapper:\n");
    s.push_str("//\n");
    s.push_str("//   auto* is = reinterpret_cast<ifc::inputsystem::CInputSystem*>(\n");
    s.push_str("//       (std::uintptr_t)GetModuleHandleA(\"inputsystem.dll\") + offsets::inputsystem::InputSystemVersion001\n");
    s.push_str("//   );\n");
    s.push_str("//   is->SetRelativeMouseMode(false);\n");
    s.push_str("//\n");
    s.push_str("// NOTE: only the primary vtable (*(void**)instance) is walked. Classes\n");
    s.push_str("// reached solely via a secondary vtable (multiple inheritance) are not\n");
    s.push_str("// covered and may be missing slots.\n");
    s.push_str("\n#pragma once\n");
    s.push_str("#include <cstdint>\n");
    s.push_str("#include <cstddef>\n\n");

    if let Some(bn) = build_number {
        writeln!(
            s,
            "namespace ifc {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n"
        )
        .ok();
    }

    // --- ifc::module::Class structs ----------------------------------------
    let mut sorted: Vec<&IfaceClass<'_>> = classes.iter().collect();
    sorted.sort_by(|a, b| (a.module, a.iface_name).cmp(&(b.module, b.iface_name)));

    // Group by RTTI class so one struct describes one vtable shape, but keep
    // every interface's own singleton RVA: sharing an RTTI class does not mean
    // sharing an instance, and the analysis pass resolves the RVA per interface.
    let mut grouped: BTreeMap<&str, BTreeMap<String, (&IfaceClass<'_>, Vec<(&str, Option<u64>)>)>> =
        BTreeMap::new();
    for c in &sorted {
        let entry = grouped
            .entry(c.module)
            .or_default()
            .entry(class_ns(c))
            .or_insert_with(|| (*c, Vec::new()));
        if !c.manual {
            entry.1.push((c.iface_name, c.instance_rva));
        }
    }

    s.push_str("namespace ifc {\n\n");
    for (module, ns_map) in &grouped {
        let mns = module_ns(module);
        writeln!(s, "    namespace {} {{", mns).ok();
        for (cns, (rep, ifaces)) in ns_map {
            let joined_ifaces = ifaces
                .iter()
                .map(|(name, _)| *name)
                .collect::<Vec<_>>()
                .join(", ");
            let iface_list = comment_text(&joined_ifaces);
            writeln!(
                s,
                "        // {} (iface: {}) | {} methods",
                cns,
                iface_list,
                rep.methods.len()
            )
            .ok();
            writeln!(s, "        struct {} {{", cns).ok();

            // Two slots can recover the same symbol, and a recovered name can
            // collide with another slot's `method_<n>` fallback. Either one
            // declared the same member twice and the struct stopped compiling,
            // so slot identifiers are allocated — the same thing `vtables.rs`
            // does with `intern_unique_ident` for this data.
            let mut method_names = IdentifierAllocator::default();
            let mut curated_slots: Vec<(usize, String)> = Vec::new();
            for m in &rep.methods {
                if let Some(cur) = curated(module, cns, m.index) {
                    let name = method_names.allocate(cur.name.to_string());
                    let params = cur
                        .params
                        .iter()
                        .enumerate()
                        .map(|(i, t)| format!("{} a{}", t, i))
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(
                        s,
                        "            virtual {} {}({}) = 0; // slot {}",
                        cur.ret, name, params, m.index
                    )
                    .ok();
                    curated_slots.push((m.index, name));
                } else if let Some(name) = m.name {
                    // Slot identified via Pattern-RVA cross-reference; args unknown.
                    let name = method_names.allocate(cpp_identifier(name));
                    writeln!(s, "            virtual void {}() = 0; // slot {} (name recovered, args unverified)", name, m.index).ok();
                } else {
                    let name = method_names.allocate(format!("method_{}", m.index));
                    writeln!(s, "            virtual void {}() = 0;", name).ok();
                }
            }
            for (index, name) in &curated_slots {
                writeln!(
                    s,
                    "            void* p{}() {{ return (*reinterpret_cast<void***>(this))[{}]; }}",
                    name, index
                )
                .ok();
            }
            writeln!(s, "        }};").ok();
        }
        writeln!(s, "    }} // namespace {}\n", mns).ok();
    }
    s.push_str("} // namespace ifc\n");

    // Additive typed singleton accessors. They take a caller-provided module
    // base, so the generated header stays ASLR-safe and remains usable from
    // external tools that obtain module handles through their own backend.
    s.push_str("\nnamespace ifc {\n");
    for (module, ns_map) in &grouped {
        let mns = module_ns(module);
        writeln!(s, "    namespace {} {{", mns).ok();
        for (cns, (rep, ifaces)) in ns_map {
            let class_name = cns;
            let fallback = [(rep.iface_name, rep.instance_rva)];
            let names: &[(&str, Option<u64>)] = if ifaces.is_empty() { &fallback } else { ifaces };
            for (iface, instance_rva) in names {
                // One interface without a resolved singleton must not take the
                // rest of its RTTI group with it, and must not borrow another
                // interface's address either.
                let Some(rva) = instance_rva else {
                    continue;
                };
                writeln!(
                    s,
                    "        inline {}* get_{}(std::uintptr_t module_base) noexcept {{ return reinterpret_cast<{}*>(module_base + 0x{:X}); }}",
                    class_name,
                    cpp_identifier(iface),
                    class_name,
                    rva
                )
                .ok();
            }
        }
        writeln!(s, "    }} // namespace {}\n", mns).ok();
    }
    s.push_str("} // namespace ifc\n");

    s.push_str("\nnamespace ifc::detail {\n");
    s.push_str("inline void* vtable_slot(void* inst, std::size_t index) noexcept {\n");
    s.push_str("    return (*reinterpret_cast<void***>(inst))[index];\n");
    s.push_str("}\n");
    s.push_str("} // namespace ifc::detail\n");
    s
}

#[cfg(test)]
mod tests {
    use super::{module_ns, render_hpp, IfaceClass, Method};
    use crate::analysis::InterfaceMap;
    use std::borrow::Cow;

    #[test]
    fn emits_aslr_safe_singleton_accessor() {
        let interfaces = InterfaceMap::new();
        let classes = vec![IfaceClass {
            module: "client.dll",
            iface_name: "Client001",
            instance_rva: Some(0x1234),
            rtti_class: Some(std::borrow::Cow::Borrowed("CClient")),
            methods: vec![Method {
                index: 0,
                name: Some("Connect"),
            }],
            manual: false,
        }];
        let output = render_hpp(&interfaces, &classes, Some(42));
        assert!(output.contains("get_Client001"));
        assert!(output.contains("module_base + 0x1234"));
        assert!(output.contains("CS2_BUILD = 42"));
        assert!(output.contains("virtual void Connect() = 0"));
    }

    #[test]
    fn module_ns_borrows_dll_stem() {
        let module = "client.dll";
        let ns = module_ns(module);
        assert_eq!(ns.as_ref(), "client");
        assert!(matches!(ns, Cow::Borrowed(_)));
        assert!(std::ptr::eq(ns.as_ref().as_ptr(), module.as_ptr()));
    }

    /// Interfaces sharing an RTTI class each resolve their own singleton, so each
    /// accessor has to use its own RVA. They used to all report the first one's.
    #[test]
    fn each_interface_accessor_uses_its_own_instance_rva() {
        let interfaces = InterfaceMap::new();
        let shared = |iface: &'static str, rva: Option<u64>| IfaceClass {
            module: "engine2.dll",
            iface_name: iface,
            instance_rva: rva,
            rtti_class: Some(Cow::Borrowed("CEngineShared")),
            methods: vec![Method {
                index: 0,
                name: None,
            }],
            manual: false,
        };
        let classes = vec![
            shared("SharedOne001", Some(0x1000)),
            shared("SharedTwo001", Some(0x2000)),
        ];
        let output = render_hpp(&interfaces, &classes, None);
        assert!(
            output.contains("get_SharedOne001(std::uintptr_t module_base) noexcept { return reinterpret_cast<CEngineShared*>(module_base + 0x1000)"),
            "{output}"
        );
        assert!(
            output.contains("get_SharedTwo001(std::uintptr_t module_base) noexcept { return reinterpret_cast<CEngineShared*>(module_base + 0x2000)"),
            "{output}"
        );
    }

    /// A group whose first interface has no resolved singleton must not take the
    /// rest of the group down with it.
    #[test]
    fn an_unresolved_first_interface_does_not_hide_its_siblings() {
        let interfaces = InterfaceMap::new();
        let shared = |iface: &'static str, rva: Option<u64>| IfaceClass {
            module: "engine2.dll",
            iface_name: iface,
            instance_rva: rva,
            rtti_class: Some(Cow::Borrowed("CEngineShared")),
            methods: Vec::new(),
            manual: false,
        };
        // Sorted by iface name, so "AAA" is the group representative.
        let classes = vec![
            shared("AAAUnresolved001", None),
            shared("ZZZResolved001", Some(0x3000)),
        ];
        let output = render_hpp(&interfaces, &classes, None);
        assert!(
            output.contains("get_ZZZResolved001"),
            "the resolved sibling lost its accessor: {output}"
        );
        assert!(
            !output.contains("get_AAAUnresolved001"),
            "an unresolved interface must not get a bogus accessor: {output}"
        );
    }

    /// Two slots recovering the same symbol used to declare the same member
    /// twice, which does not compile.
    #[test]
    fn slots_recovering_the_same_name_are_disambiguated() {
        let interfaces = InterfaceMap::new();
        let classes = vec![IfaceClass {
            module: "client.dll",
            iface_name: "Client001",
            instance_rva: Some(0x10),
            rtti_class: Some(Cow::Borrowed("CClient")),
            methods: vec![
                Method {
                    index: 0,
                    name: Some("Frame"),
                },
                Method {
                    index: 1,
                    name: Some("Frame"),
                },
            ],
            manual: false,
        }];
        let output = render_hpp(&interfaces, &classes, None);
        assert_eq!(
            output.matches("virtual void Frame() = 0").count(),
            1,
            "the duplicate must be renamed, not declared twice: {output}"
        );
        assert!(output.contains("virtual void Frame_2() = 0"), "{output}");
    }
}
