//! Netvar / `MNetworkVarNames` extractor + emitter.
//!
//! # Background
//!
//! Source 2 marks every networked field on every entity with a
//! `MNetworkVarNames(<schema_name>, <type_name>)` metadata entry on its
//! enclosing class. The schema dump already captures this metadata —
//! this emitter just splits it out into its own file so internals don't
//! have to dig through the (large) schema dump to find network-relevant
//! fields.
//!
//! # Output
//!
//! Each call writes:
//!
//! - `netvars.json` — `{ class_name: { field_name: { offset, type } } }`
//! - `netvars.hpp`  — `inline constexpr std::ptrdiff_t` per field, namespaced
//! - `netvars.cs`   — same as `.hpp` for C# consumers
//!
//! The grouping is by class, not by module, because internal cheats
//! generally lookup netvars by `(class, field)` pair regardless of which
//! DLL the class came from.

use std::collections::BTreeMap;
use std::fmt::Write;

use rayon::prelude::*;
use serde_json::json;

use crate::analysis::{ClassMetadata, SchemaMap};

use super::ident::{cpp_identifier, type_ident, IdentifierAllocator};
use super::comment_text;

/// Extracted view of one networked field.
///
/// Strings borrow the schema dump — class names are not cloned once per field.
#[derive(Debug, Clone, Copy)]
pub struct NetVar<'a> {
    pub class: &'a str,
    pub field: &'a str,
    pub offset: i32,
    pub type_name: &'a str,
}

/// Walk the schema and pull out every field that has a matching
/// `MNetworkVarNames` metadata entry.
///
/// The metadata is keyed by *field name* and applies to the same class
/// — the schema parser already attached the metadata list to each class,
/// so all we have to do is filter and zip with the matching field.
pub fn extract(schemas: &SchemaMap) -> Vec<NetVar<'_>> {
    let mut out: Vec<NetVar<'_>> = schemas
        .par_iter()
        .flat_map(|(_, (classes, _))| {
            classes
                .par_iter()
                .flat_map(|class| {
                    class
                        .metadata
                        .iter()
                        .filter_map(|meta| {
                            let ClassMetadata::NetworkVarNames { name, type_name } = meta else {
                                return None;
                            };
                            let field = class.fields.iter().find(|f| &f.name == name)?;
                            Some(NetVar {
                                class: class.name.as_str(),
                                field: name.as_str(),
                                offset: field.offset,
                                type_name: type_name.as_str(),
                            })
                        })
                        .collect::<Vec<_>>()
                })
                .collect::<Vec<_>>()
        })
        .collect();
    out.par_sort_unstable_by(|a, b| (a.class, a.field).cmp(&(b.class, b.field)));
    out
}

/// Group [`NetVar`]s by class for emitters that nest per-class.
fn grouped<'a>(netvars: &'a [NetVar<'a>]) -> BTreeMap<&'a str, Vec<&'a NetVar<'a>>> {
    let mut out: BTreeMap<&str, Vec<&NetVar<'_>>> = BTreeMap::new();
    for n in netvars {
        out.entry(n.class).or_default().push(n);
    }
    out
}

/// Emit a JSON document keyed by class then field.
pub fn render_json(netvars: &[NetVar<'_>]) -> Result<String, serde_json::Error> {
    let mut by_class: BTreeMap<&str, BTreeMap<&str, serde_json::Value>> = BTreeMap::new();
    for n in netvars {
        by_class
            .entry(n.class)
            .or_default()
            .insert(n.field, json!({ "offset": n.offset, "type": n.type_name }));
    }
    serde_json::to_string_pretty(&by_class)
}

/// Emit a C++ header: `sdk::netvars::<class>::<field>`.
pub fn render_hpp(netvars: &[NetVar<'_>], build_number: Option<u32>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("#pragma once\n\n");
    s.push_str("#include <cstddef>\n#include <cstdint>\n\n");
    if let Some(bn) = build_number {
        writeln!(
            s,
            "namespace netvar {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n"
        )
        .ok();
    }
    s.push_str("namespace netvar {\n\n");
    let mut class_names = IdentifierAllocator::default();
    for (class, fields) in grouped(netvars) {
        let class_ident =
            class_names.allocate(cpp_identifier(type_ident(class).as_ref()));
        writeln!(s, "    namespace {class_ident} {{").ok();
        let mut field_names = IdentifierAllocator::default();
        for n in fields {
            writeln!(
                s,
                "        inline constexpr std::ptrdiff_t {:<48} = {:#X}; // {}",
                field_names.allocate(cpp_identifier(n.field)),
                n.offset,
                comment_text(n.type_name),
            )
            .ok();
        }
        writeln!(s, "    }} // namespace {class_ident}\n").ok();
    }
    s.push_str("} // namespace netvar\n");
    s
}

#[cfg(test)]
mod tests {
    use super::extract;
    use crate::analysis::{Class, ClassField, ClassMetadata, SchemaMap};

    #[test]
    fn extract_keeps_network_var_offset_and_skips_unmatched_metadata() {
        let health_offset = 0x4A8;
        let schemas = SchemaMap::from([(
            "client.dll".to_string(),
            (
                vec![Class {
                    name: "C_TestPawn".into(),
                    module_name: "client.dll".into(),
                    parent_name: None,
                    size: 0x500,
                    alignment: 8,
                    metadata: vec![
                        ClassMetadata::NetworkVarNames {
                            name: "m_iHealth".into(),
                            type_name: "int32".into(),
                        },
                        ClassMetadata::NetworkVarNames {
                            name: "m_missing".into(),
                            type_name: "int32".into(),
                        },
                    ],
                    fields: vec![ClassField {
                        name: "m_iHealth".into(),
                        type_name: "int32".into(),
                        offset: health_offset,
                        metadata: Vec::new(),
                    }],
                    static_fields: Vec::new(),
                    flags: Vec::new(),
                }],
                Vec::new(),
            ),
        )]);
        let found = extract(&schemas);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].class, "C_TestPawn");
        assert_eq!(found[0].field, "m_iHealth");
        assert_eq!(found[0].offset, health_offset);
        assert_eq!(found[0].type_name, "int32");
        let class = &schemas["client.dll"].0[0];
        assert!(std::ptr::eq(found[0].class.as_ptr(), class.name.as_ptr()));
        let meta_name = class.metadata.iter().find_map(|meta| match meta {
            ClassMetadata::NetworkVarNames { name, .. } if name == "m_iHealth" => {
                Some(name.as_str())
            }
            _ => None,
        });
        assert!(std::ptr::eq(
            found[0].field.as_ptr(),
            meta_name.expect("network var metadata").as_ptr()
        ));
    }
}
