//! Multi-language emitters for resolved patterns.
//!
//! We already emit a hand-formatted `patterns.json`. This module adds
//! sibling files in the same set of languages the offset pass produces
//! (`.hpp`, `.rs`, `.cs`, `.zig`) so consumers can drop the file straight into
//! their project without writing a converter.
//!
//! Output is intentionally minimal — one constant per Pattern, named
//! after the Pattern, valued with the IDA-style byte **pattern**
//! (auto-synthesised at the resolved RVA when available, otherwise the
//! database pattern).  Consumers do their own pattern scanning at
//! runtime, which is build-portable and avoids leaking absolute
//! addresses into compiled artefacts.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::output::ident::{
    IdentifierAllocator, cpp_identifier, csharp_identifier, rust_identifier, slugify,
};
use crate::output::zig_ident;

use super::PatternHit;

/// Group resolved patterns by module so each emitter can render them as
/// nested namespaces / modules / classes. RIPREL (data-global) sigs are
/// included: their `pattern_synth` is null so `emit_pattern` yields the raw
/// instruction needle, which consumers scan and rip-resolve themselves.
fn grouped<'a>(hits: &'a [PatternHit]) -> BTreeMap<&'a str, Vec<&'a PatternHit>> {
    let mut out: BTreeMap<&'a str, Vec<&'a PatternHit>> = BTreeMap::new();
    for h in hits.iter().filter(|h| h.found) {
        out.entry(h.module.as_ref()).or_default().push(h);
    }
    for v in out.values_mut() {
        v.sort_by(|a, b| {
            (a.name.as_ref(), a.rva, a.pattern.as_ref()).cmp(&(
                b.name.as_ref(),
                b.rva,
                b.pattern.as_ref(),
            ))
        });
        // Collapse only hits that are the same symbol resolved to the same place.
        // A display name is the database name minus its C++ class prefix, so
        // distinct functions share one: `CHLTVClient_ExecuteStringCommand` and
        // `CServerSideClient_ExecuteStringCommand` both reduce to
        // `ExecuteStringCommand`, at different addresses. Dropping either one
        // silently handed the consumer the other function's pattern. The
        // emitters below allocate identifiers, so a genuine collision comes out
        // as `<Name>_2` — visible — instead of vanishing.
        v.dedup_by(|a, b| a.name == b.name && a.rva == b.rva && a.pattern == b.pattern);
    }
    out
}

fn module_stem(module: &str) -> &str {
    module.trim_end_matches(".dll")
}

/// Pick the pattern string we want to emit for a given hit.  We prefer
/// the auto-synthesised IDA pattern at the resolved RVA (handles
/// `StringRef` entries whose database `pattern` is text, not bytes),
/// and fall back to the database pattern when `.text` was outside the
/// scanned range (rare).
fn emit_pattern(h: &PatternHit) -> Option<&str> {
    if let Some(p) = h.pattern_synth.as_deref() {
        return Some(p);
    }
    // Skip StringRef when no synth — its `pattern` field is the literal
    // string, not a byte pattern, so it would never scan-match.
    if h.resolve == "StringRef" || h.resolve == "stringref" {
        return None;
    }
    Some(h.pattern.as_ref())
}

/// C++ header with one `inline constexpr` IDA-style pattern per
/// Pattern, namespaced per module.  In addition to the pattern
/// strings we emit a sibling `using <Name>_t = void(__fastcall*)(...);`
/// function-pointer typedef for every Pattern so consumers can write
/// `auto fn = reinterpret_cast<cs2::fn::client_dll::CreateMove_t>(scan(...));`
/// without re-typing the calling convention.  We don't know the real
/// argument list (this would require type recovery from IDA / a
/// debugger), so the typedef is intentionally generic
/// (`void __fastcall(void*, ...)`) and the consumer can
/// `reinterpret_cast` it to a more specific shape when they hook.
pub fn render_hpp(hits: &[PatternHit]) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk — https://cs2-sdk.com\n");
    s.push_str("// Each constant is an IDA-style byte pattern; scan it at\n");
    s.push_str("// runtime with your favourite pattern scanner.\n");
    s.push_str("#pragma once\n\n#include <string_view>\n\n");
    s.push_str("namespace pattern {\n");
    let mut modules = IdentifierAllocator::default();
    for (module, items) in grouped(hits) {
        let module_name = modules.allocate(cpp_identifier(module_stem(module)));
        let _ = writeln!(s, "    namespace {module_name} {{");
        let mut names = IdentifierAllocator::default();
        for h in &items {
            let Some(pattern) = emit_pattern(h) else {
                continue;
            };
            let _ = writeln!(
                s,
                "        inline constexpr std::string_view {} = \"{}\";",
                names.allocate(cpp_identifier(&h.name)),
                pattern,
            );
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

pub fn render_rs(hits: &[PatternHit]) -> String {
    let mut s =
        String::from("// Generated by cs2-dumper. IDA-style patterns for runtime scanning.\n\n");
    let mut modules = IdentifierAllocator::default();
    for (module, items) in grouped(hits) {
        let module_name = modules.allocate(rust_identifier(module_stem(module)));
        let _ = writeln!(s, "pub mod {module_name} {{");
        let mut names = IdentifierAllocator::default();
        for h in items {
            if let Some(pattern) = emit_pattern(h) {
                let _ = writeln!(
                    s,
                    "    pub const {}: &str = {:?};",
                    names.allocate(rust_identifier(&h.name)),
                    pattern
                );
            }
        }
        s.push_str("}\n\n");
    }
    s
}

pub fn render_cs(hits: &[PatternHit]) -> String {
    let mut s = String::from(
        "// Generated by cs2-dumper. IDA-style patterns for runtime scanning.\n\npublic static class Patterns\n{\n",
    );
    let mut modules = IdentifierAllocator::default();
    for (module, items) in grouped(hits) {
        let module_name = modules.allocate(csharp_identifier(module_stem(module)));
        let _ = writeln!(s, "    public static class {module_name}\n    {{");
        let mut names = IdentifierAllocator::default();
        for h in items {
            if let Some(pattern) = emit_pattern(h) {
                let _ = writeln!(
                    s,
                    "        public const string {} = {:?};",
                    names.allocate(csharp_identifier(&h.name)),
                    pattern
                );
            }
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

pub fn render_zig(hits: &[PatternHit]) -> String {
    let mut s =
        String::from("// Generated by cs2-dumper. IDA-style patterns for runtime scanning.\n\n");
    let mut modules = IdentifierAllocator::default();
    for (module, items) in grouped(hits) {
        let module_name = modules.allocate(slugify(module_stem(module)).into_owned());
        let module_name = zig_ident(&module_name);
        let _ = writeln!(s, "pub const {module_name} = struct {{");
        let mut names = IdentifierAllocator::default();
        for h in items {
            if let Some(pattern) = emit_pattern(h) {
                let name = names.allocate(slugify(&h.name).into_owned());
                let _ = writeln!(s, "    pub const {} = {:?};", zig_ident(&name), pattern);
            }
        }
        s.push_str("};\n\n");
    }
    s
}

fn md_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

/// Human-readable signature inventory for patch-day review.
pub fn render_md(hits: &[PatternHit]) -> String {
    let mut s = String::from(
        "# Resolved Patterns\n\n| Module | Name | Status | Resolve | Matches | Confidence | Match RVA | RVA | Pattern / Error |\n|---|---|---:|---|---:|---:|---:|---:|---|\n",
    );
    let mut sorted = hits.iter().collect::<Vec<_>>();
    sorted.sort_by(|a, b| a.module.cmp(&b.module).then(a.name.cmp(&b.name)));
    for hit in sorted {
        let status = if hit.found { "found" } else { "missing" };
        let pattern_or_error = if hit.found {
            hit.pattern.as_ref()
        } else {
            hit.error.as_deref().unwrap_or("unknown error")
        };
        let match_rva = hit
            .match_rva
            .map(|v| format!("0x{v:X}"))
            .unwrap_or_else(|| "-".to_string());
        let rva = hit
            .rva
            .map(|v| format!("0x{v:X}"))
            .unwrap_or_else(|| "-".to_string());
        let _ = writeln!(
            s,
            "| {} | {} | {} | {} | {} | {:.3} | {} | {} | {} |",
            md_cell(&hit.module),
            md_cell(&hit.name),
            status,
            hit.resolve,
            hit.matches,
            hit.confidence,
            match_rva,
            rva,
            md_cell(pattern_or_error),
        );
    }
    s
}

#[cfg(test)]
mod tests {
    use super::{render_cs, render_hpp, render_md, render_rs, render_zig};
    use crate::patterns::PatternHit;

    fn hit() -> PatternHit {
        PatternHit {
            name: "Example".into(),
            module: "client.dll".into(),
            resolve: "raw",
            pattern: "48 8B ??".into(),
            prototype: None,
            bytes: None,
            pattern_synth: Some("48 8B 01".to_string()),
            repaired_from: None,
            found: true,
            match_rva: Some(16),
            match_va: Some(32),
            rva: Some(16),
            va: Some(32),
            matches: 1,
            confidence: 1.0,
            error: None,
        }
    }
    #[test]
    fn renders_supported_language_outputs() {
        let hits = [hit()];
        for rendered in [render_rs(&hits), render_cs(&hits), render_zig(&hits)] {
            assert!(rendered.contains("Example"));
            assert!(rendered.contains("48 8B 01"));
        }
        assert!(render_md(&hits).contains("| client.dll | Example | found |"));
        assert!(render_md(&hits).contains("1.000"));
    }

    /// A display name is the database name with its C++ class prefix stripped,
    /// so two different functions share one. Dropping either would hand the
    /// consumer the other function's pattern under a name it trusts; a real
    /// collision has to stay visible as `<Name>_2`.
    #[test]
    fn two_functions_sharing_a_display_name_both_survive() {
        let mut hltv = hit();
        hltv.name = "ExecuteStringCommand".into();
        hltv.module = "engine2.dll".into();
        hltv.rva = Some(0x1000);
        hltv.pattern_synth = Some("48 89 5C 24 08".to_string());

        let mut server_side = hit();
        server_side.name = "ExecuteStringCommand".into();
        server_side.module = "engine2.dll".into();
        server_side.rva = Some(0x2000);
        server_side.pattern_synth = Some("40 55 41 56".to_string());

        let hits = [hltv, server_side];
        for rendered in [
            render_hpp(&hits),
            render_rs(&hits),
            render_cs(&hits),
            render_zig(&hits),
        ] {
            assert!(
                rendered.contains("48 89 5C 24 08") && rendered.contains("40 55 41 56"),
                "both patterns must be emitted: {rendered}"
            );
            assert!(
                rendered.contains("ExecuteStringCommand_2"),
                "the second one needs a disambiguated name: {rendered}"
            );
        }
    }

    /// The same symbol reported twice at the same address is noise, not data —
    /// that one still collapses.
    #[test]
    fn an_identical_hit_reported_twice_is_emitted_once() {
        let hits = [hit(), hit()];
        let hpp = render_hpp(&hits);
        assert_eq!(hpp.matches("Example").count(), 1, "{hpp}");
        assert!(!hpp.contains("Example_2"), "{hpp}");
    }

    #[test]
    fn source_outputs_escape_keywords_and_disambiguate_collisions() {
        let mut hits = Vec::new();
        for name in ["struct", "_struct", "foo-bar", "foo_bar"] {
            let mut value = hit();
            value.name = name.into();
            value.module = "mod.dll".into();
            hits.push(value);
        }
        for module in ["foo-bar.dll", "foo_bar.dll"] {
            let mut value = hit();
            value.name = "Unique".into();
            value.module = module.into();
            hits.push(value);
        }

        let hpp = render_hpp(&hits);
        assert!(hpp.contains("_struct_2"), "C++ keyword collision: {hpp}");
        assert!(hpp.contains("foo_bar_2"), "C++ collision: {hpp}");
        let rust = render_rs(&hits);
        assert!(rust.contains("pub mod _mod"), "Rust module keyword: {rust}");
        assert!(rust.contains("_struct_2"), "Rust keyword collision: {rust}");
        assert!(rust.contains("foo_bar_2"), "Rust collision: {rust}");
        let csharp = render_cs(&hits);
        assert!(
            csharp.contains("_struct_2"),
            "C# keyword collision: {csharp}"
        );
        assert!(csharp.contains("foo_bar_2"), "C# collision: {csharp}");
        let zig = render_zig(&hits);
        assert!(
            zig.contains("@\"struct\""),
            "Zig keyword was not escaped: {zig}"
        );
        assert!(zig.contains("foo_bar_2"), "Zig collision: {zig}");
    }
}
